function(gura_link_llvm target)
  find_package(LLVM CONFIG QUIET)
  if(LLVM_FOUND)
    message(STATUS "Found LLVM ${LLVM_PACKAGE_VERSION}")
    target_include_directories(${target} SYSTEM PRIVATE ${LLVM_INCLUDE_DIRS})
    target_compile_definitions(${target} PRIVATE ${LLVM_DEFINITIONS} GURA_HAS_LLVM=1)
    llvm_map_components_to_libnames(GURA_LLVM_LIBS core support irreader nativecodegen target)
    target_link_libraries(${target} PRIVATE ${GURA_LLVM_LIBS})
  else()
    message(WARNING "LLVM package not found; building LLVM codegen stub only")
    target_compile_definitions(${target} PRIVATE GURA_HAS_LLVM=0)
  endif()
endfunction()
